// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZHHIFxDWcDD_WdvaZz-WqDUGR-jITdA',
    appId: '1:495139000181:web:c7f53e1c8b9a50e98acd3c',
    messagingSenderId: '495139000181',
    projectId: 'ombe-coffe-app',
    authDomain: 'ombe-coffe-app.firebaseapp.com',
    storageBucket: 'ombe-coffe-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12968wqS8cWfSZ7L7B7EQ33aHoexz5wU',
    appId: '1:495139000181:android:c2e6237177780cbf8acd3c',
    messagingSenderId: '495139000181',
    projectId: 'ombe-coffe-app',
    storageBucket: 'ombe-coffe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4DiirAyc311NiG-VENHnCWVGP-FlFjCQ',
    appId: '1:495139000181:ios:85ea1a06e242e73d8acd3c',
    messagingSenderId: '495139000181',
    projectId: 'ombe-coffe-app',
    storageBucket: 'ombe-coffe-app.firebasestorage.app',
    iosBundleId: 'com.example.coffeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4DiirAyc311NiG-VENHnCWVGP-FlFjCQ',
    appId: '1:495139000181:ios:85ea1a06e242e73d8acd3c',
    messagingSenderId: '495139000181',
    projectId: 'ombe-coffe-app',
    storageBucket: 'ombe-coffe-app.firebasestorage.app',
    iosBundleId: 'com.example.coffeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcZHHIFxDWcDD_WdvaZz-WqDUGR-jITdA',
    appId: '1:495139000181:web:95ada40aca205bbd8acd3c',
    messagingSenderId: '495139000181',
    projectId: 'ombe-coffe-app',
    authDomain: 'ombe-coffe-app.firebaseapp.com',
    storageBucket: 'ombe-coffe-app.firebasestorage.app',
  );
}
